main: github.PlaytimeRegulator.PlaytimeRegulator
version: 0.1
api-version: 1.16
name: PlaytimeRegulator
author: Cinnazeyy
depend:

commands:
  ptreset:
    description: Resets all playtime
    usage: /ptreset
    permission: playtime.admin